import { app, BrowserWindow, ipcMain, desktopCapturer, shell } from 'electron';
import { exec } from 'child_process';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Set Content Security Policy to allow WebSocket connections
  mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': ["default-src 'self' 'unsafe-inline' 'unsafe-eval' data: ws: wss: http: https:"]
      }
    });
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// IPC handler for screenshot capture
ipcMain.handle('capture-screenshot', async () => {
  try {
    const sources = await desktopCapturer.getSources({
      types: ['screen'],
      thumbnailSize: { width: 1920, height: 1080 },
    });

    if (sources.length === 0) {
      return { error: 'Screen Recording permission denied', needsPermission: true };
    }

    const screenshot = sources[0].thumbnail;
    const pngBuffer = screenshot.toPNG();
    const base64 = pngBuffer.toString('base64');

    return {
      image: base64,
      timestamp: new Date().toISOString(),
    };
  } catch (error) {
    const errorMsg = String(error);
    console.error('Screenshot capture failed:', errorMsg);
    // "Failed to get sources" typically means permission denied on macOS
    const needsPermission = errorMsg.toLowerCase().includes('failed to get sources');
    return { error: errorMsg, needsPermission };
  }
});

// IPC handler for opening system preferences
ipcMain.handle('open-system-preferences', async () => {
  if (process.platform === 'darwin') {
    await shell.openExternal('x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture');
  }
});

// IPC handler for getting active window (macOS)
ipcMain.handle('get-active-window', async () => {
  return new Promise((resolve) => {
    if (process.platform !== 'darwin') {
      resolve({ appName: 'Unknown', windowTitle: 'Unknown', error: 'Not supported' });
      return;
    }

    // Get the frontmost application name
    exec('osascript -e \'tell app "System Events" to get name of first process whose frontmost is true\'', (err, stdout) => {
      const appName = stdout.trim() || 'Unknown';
      
      // Try to get window title (limited support)
      exec(`osascript -e 'tell app "${appName}" to get name of first window'`, (err2, stdout2) => {
        const windowTitle = err2 ? '' : stdout2.trim();
        
        resolve({
          appName,
          windowTitle: windowTitle || '',
          timestamp: new Date().toISOString(),
        });
      });
    });
  });
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
